-- INSERT INTO PERSON (id, username, email, password, role)
-- VALUES (1, 'john_doe', 'john@example.com', 'password123', 'USER'),
--        (2, 'jane_admin', 'jane@example.com', 'securePass!', 'ADMIN'),
--        (3, 'alex_smith', 'alex@example.com', 'alexPass!', 'USER'),
--        (4, 'emily_white', 'emily@example.com', 'emily123', 'USER');
